### PR TITLE
exTHm-ify

### PR DESCRIPTION
**Pull request by Anaple**

### CODE REVIEW

**Comment by mueslo** [comment]
lol

**Comment by djdelarosa25** [comment]
lol (x2)

**Comment by hh2333** [comment]
lmao

**Comment by 18796299507** [comment]
万物皆可ify

**Comment by gotenksIN** [comment]
smh

**Comment by ALKALiKong233** [comment]
LMFAO 🤣🤣🤣

**Comment by adi8900** [comment]
Lol

**Pull request closed without merging**
